### ISSUE TITLE
Some language names start with 10 - 

### ISSUE THREAD

**Issue by pdr** [highfestiva/bcp47.py#1]
Example here:
https://github.com/highfestiva/bcp47.py/blob/master/bcp47/bcp47.py#L42

Is this normal or a typo?

**Comment by pdr** [comment]
It looks like there are 6 instances.

Also thank you for publishing this package.

**Comment by highfestiva** [comment]
Thanks, you're right, sorry about that. I was in a hurry in the first implementation. This time I went over the resulting table carefully and everything looks nice. Thanks for the pat on the back, btw!
It's pipped to v0.0.2.
