### ISSUE TITLE
Few languages don't show up.

### ISSUE THREAD

**Issue by mxav1111** [highfestiva/bcp47.py#4]
It seems this might require an update since few languages aren't showing up that shows up in language_tags. Please consider as i am not very familiar with correcting/updating.

'ar-XA'  should come up with key like Arabic
'cmn-CN'  should come up with key like -- 'Mandarin Chinese', 'China'
'cmn-TW' should come up with key like -- 'Mandarin Chinese', 'Taiwan, Province of China'
'sr-RS'      should come up with key like -- 'Serbian', 'Serbia'
'yue-HK'      should come up with key like -- 'Yue Chinese', 'Cantonese', 'Hong Kong'

For now, commented the import of bcp47 and using language_tags although it seems bcp47 is showing up as newer one.

**Comment by highfestiva** [comment]
The tags come from this MS document: https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-LCID/[MS-LCID].pdf. There are probably others missing too. They've done updates to the document, but it's still lacking.

**Comment by highfestiva** [comment]
XA seems to be a Russian notation for Abkhazia, mandarin are not mentioned in any of the language tables I've seen (in fact simplified Chinese is the only one I've noticed), Hong Kong has now been enslaved by China, and Serbian doesn't seem to have that language code at all (it's either "sr" or "sr-Latn-RS").
